#!/usr/bin/env python3
"""TBD"""
# pylint: disable=invalid-name,broad-except,too-many-instance-attributes

import os
import sys
import time
import subprocess
import traceback
import argparse
from types import SimpleNamespace
import termios
import tty
import shutil
import signal

####################################################################################

class Term:
    """ Escape sequences; e.g., see:
     - https://en.wikipedia.org/wiki/ANSI_escape_code
     - https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797#file-ansi-md
    """
    esc = '\x1B'
    # pylint: disable=missing-function-docstring,multiple-statements
    @staticmethod
    def erase_line(): return f'{Term.esc}[2K'
    @staticmethod
    def reverse_video(): return f'{Term.esc}[7m'
    @staticmethod
    def normal_video(): return f'{Term.esc}[m'
    @staticmethod
    def pos_up(cnt): return f'{Term.esc}[{cnt}F' if cnt > 0 else ''
    @staticmethod
    def pos_down(cnt): return f'{Term.esc}[{cnt}E' if cnt > 0 else ''
    @staticmethod
    def col(pos): return f'{Term.esc}[{pos}G'
    @staticmethod
    def clear_screen(): return f'{Term.esc}[H{Term.esc}[2J{Term.esc}[3J'

####################################################################################

class Menu:
    """ A simple menu system """
    fd = sys.stdin.fileno()
    save_attrs = None
    class InputTimeout(Exception):
        """ Raised for obvious reasons. """

    @staticmethod
    def prompt_mode(enable=False):
        """ TBD """
        if enable:
            if not Menu.save_attrs:
                Menu.save_attrs = termios.tcgetattr(Menu.fd)
                tty.setcbreak(Menu.fd)
        else:
            if Menu.save_attrs:
                termios.tcsetattr(Menu.fd, termios.TCSADRAIN, Menu.save_attrs)
                Menu.save_attrs = None

    def __init__(self, prompts):
        self.prompts = prompts
        self.lines = []
        self.selected = len(prompts)
        self.pos = 0
        self.cols, self.rows = shutil.get_terminal_size()
        self.max_line = 0
        print('\n'*len(prompts))
        # time.sleep(10)
        self.pos = len(prompts)
        for idx, (key, prompt) in enumerate(prompts.items()):
            self.lines.append(f'{key}: {prompt}')
            action = self.draw_line_str(idx)
            print(action, end='', flush=True) # 1st time with newline to advance pos
            # print(action) # 1st time with newline to advance pos
        self.bottom_line(f'Highlight w Up/Down/key and Enter{Term.col(0)}')
        self.input = ''
        self.bottom = ''

    def refresh(self):
        """ TBD """
        print(Term.clear_screen(), end='', flush=True)
        for idx in range(0, len(self.lines)+1):
            print(self.draw_line_str(idx), end='', flush=True)
        self.bottom_line(self.bottom, do_prefix=False)
        print(self.set_pos_str(self.selected), end='', flush=True)

    def set_pos_str(self, idx):
        """ Goto the given line from where we are at."""
        idx = 0 if idx < 0 else len(self.lines) if idx > len(self.lines) else idx
        if idx == self.pos:
            return ''
        if idx < self.pos:
            self.pos, cnt = idx, self.pos - idx
            return Term.pos_up(cnt)
        self.pos, cnt = idx, idx - self.pos
        return Term.pos_down(cnt)

    def draw_line_str(self, idx):
        """Draw the menu or a subset"""
        idx = 0 if idx < 0 else len(self.lines) if idx > len(self.lines) else idx
        action, pre, on, off = '', ' ', '', ''
        if idx == self.selected and idx < len(self.lines):
            pre, on, off = '>',Term.reverse_video(), Term.normal_video()
        if idx < len(self.lines):
            self.max_line = max(2+len(self.lines[idx]), self.max_line)
            action += self.set_pos_str(idx)
            action += Term.erase_line()
            line = self.lines[idx][:self.cols-2]
            action += f'{pre} {on}{line}{off}'
            action += Term.col(0)
        return action

    def move(self, cnt):
        """ TBD """
        action = ''
        idx = self.selected + cnt
        idx = 0 if idx < 0 else len(self.lines) if idx > len(self.lines) else idx
        if idx != self.selected:
            was_selected, self.selected = self.selected, idx
            action += self.draw_line_str(was_selected)
            action += self.draw_line_str(self.selected)
            action += self.set_pos_str(self.selected)
            print(action, end='', flush=True)

    def get_char(self):
        """ Get one char from stdin """
        def init_timeout_handling():
            # `SIGWINCH` is send on terminal resizes
            def handle_timeout(*ignore):
                raise Menu.InputTimeout
            signal.signal(signal.SIGALRM, handle_timeout)
            signal.setitimer(signal.ITIMER_REAL, 0.25, 0.25)

        def reset_timeout_handling() -> None:
            signal.setitimer(signal.ITIMER_REAL, 0, 0)
            signal.signal(signal.SIGALRM, signal.SIG_IGN)

        rv = None
        init_timeout_handling()
        while True:
            try:
                init_timeout_handling()
                rv = sys.stdin.read(1)
                reset_timeout_handling()
            except Menu.InputTimeout:
                reset_timeout_handling()
            except Exception as caught:
                reset_timeout_handling()
                raise caught

            reset_timeout_handling()
            cols, rows = shutil.get_terminal_size()
            if self.cols != cols or self.rows != rows:
                self.cols, self.rows = cols, rows
                self.bottom_line(f'resize: rows={self.rows}, cols={self.cols}')
                self.refresh()
            if rv is not None:
                return rv

    def bottom_line(self, string, do_prefix=True):
        """ TBD """
        prefix = ''
        if do_prefix:
            prefix = '::::::'
        action = self.set_pos_str(len(self.lines))
        action += Term.erase_line()
        self.bottom = f'{prefix} {string}'
        action += self.bottom[:self.cols-1]
        action += self.set_pos_str(self.selected)
        action += Term.col(0)
        print(action, end='', flush=True)

    def finish(self, string):
        """ TBD """
        cnt = 1 + len(self.lines) - self.selected
        action = Term.pos_down(cnt)
        action += f'{string}'
        print(action, flush=True)

    def prompt(self):
        """ TBD """
        while True:
            try:
                self.prompt_mode(enable=True)
                ans = ''
                while True:
                    key = self.get_char()
                    ans += key
                    if key.isalnum() or key in ('\n', ' '):
                        break
                if ans in ('\033[A', '\033[C'):
                    self.move(-1)
                elif ans in ('\033[B', '\033[C'):
                    self.move(1)
                elif ans in ('\n', ' '):
                    if self.selected < len(self.lines):
                        picked = list(self.prompts.keys())[self.selected]
                        self.prompt_mode(enable=False)
                        # self.finish(f'\n\nrunning {repr(picked)}')
                        self.finish('')
                        return picked
                    self.bottom_line('invalid(no selection); pick again')
                elif ans in self.prompts:
                    idx = list(self.prompts.keys()).index(ans)
                    self.move(idx - self.selected)
                else:
                    self.bottom_line(f'invalid({repr(ans)}); pick again')
            finally:
                self.prompt_mode(enable=False)

####################################################################################

def run_primitive(subcmd, tout=None):
    """ run shell command
    @param subcmd: sub-command to execute
    @param tout: timeout for command execution
    @return: (return code from command, command output)
    """
    # pylint: disable=consider-using-with
    cmd = 'bash ~/.local/bin/maintcli ' + subcmd
    # do not redirect stderr if passwd cmd or prompt does not show
    stderr = None if 'set-password-' in subcmd else subprocess.STDOUT
    p = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=stderr)
    output = ''
    for line in p.stdout:
        try:
            line = line.decode(errors='replace' if (sys.version_info) < (3, 5)
                    else 'backslashreplace').rstrip()
            output += line
            print(line)
        except KeyboardInterrupt:
            pass

    retval = None
    while retval is None:
        try:
            retval = p.wait(tout)
        except KeyboardInterrupt:
            pass
    return (retval, output)

def run_prompt():
    """TBD"""
    _, _ = run_primitive('get-state', None)
    print('----------- READY --------------\n')

def run_subcmd(subcmd, tout=None):
    """Run command with decoration"""
    print('      --------------------------')
    retval, output = run_primitive(subcmd, tout)
    print(f'\n----------- {subcmd} DONE --------------\n')
    # run_prompt()
    return (retval, output)

def get_state():
    """TBD"""
    try:
        with open('/dev/.cros_milestone', mode='r', encoding='utf-8') as fhandle:
            lines = fhandle.readlines()
    except Exception:
        lines = ['Unknown Version']
    try:
        with open('/etc/apt/sources.list', mode='r', encoding='utf-8') as fhandle:
            text = fhandle.read()
    except Exception:
        text = ''

    version = lines[0]
    if 'unstable' in text:
        release = 'unstable'
    elif 'testing' in text:
        release = 'testing'
    else:
        release = 'stable'

    which_fp = os.system('which flatpak > /dev/null 2>&1')
    backend_fp = os.system('dpkg-query -W plasma-discover-backend-flatpak > /dev/null 2>&1')
    is_flatpak = 'on' if bool(which_fp == 0 and backend_fp == 0) else 'off'

    libofc_lock = 'n/a'
    if os.system('which soffice > /dev/null 2>&1') == 0:
        libofc_lock = 'on'
        if os.system("grep -qs '#.*_ENABLE_FILE_LOCKING' $(which soffice)") == 0:
            libofc_lock = 'off'

    state = SimpleNamespace(ver=version, rel=release,
        flatpak=is_flatpak, libofc=libofc_lock)
    return state

def main():
    """TBD"""
    parser = argparse.ArgumentParser()
    parser.add_argument('-e', '--every', action='store_true',
             help='show every choice even if inapplicable')
    parser.add_argument('-n', '--dry-run', action='store_true',
             help='do NOT actually run tasks')
    args = parser.parse_args()

    while True:
        state = get_state()
        print(f'\n=== MaintMenu: ChromeOS=v{state.ver} DebRelease={state.rel} Flatpak={state.flatpak}',
            '' if state.libofc == 'n/a' else f'LibOfcLock={state.libofc}', '===')
        every = args.every
        dry_run = args.dry_run
        opts = {
            'q': 'Quit',
            'A': 'Set root password',
            'B': 'Set current user password',
            'u': 'Update Linux -- run after ChromeOS update (at least)',
            'r': 'Refresh Icons -- fix cases of icons becoming lost',
        }
        if every or state.flatpak == 'off':
            opts['f'] = 'Enable Flatpak -- w Discover support (more steps in README)'
        if every or state.flatpak != 'off':
            opts['c'] = 'Cleanup Flatpak -- clean disk after uninstalling FlatPak apps'
            opts['p'] = 'Purge Flatpak -- remove FlatPak apps and disable its support'
        if every or state.libofc == 'on':
            opts['l'] = 'Disable LibreOffice File Locking -- enable GDrive (more steps in README)'
        if every or state.rel in ('stable', 'unstable'):
            opts['t'] = 'Debian Testing -- switch to Testing release'
        if every or state.rel in ('stable', 'testing'):
            opts['s'] = 'Debian Unstable -- switch to Unstable release (a.k.a., Sid)'
        menu = Menu(opts)
        picked = opts[menu.prompt()]
        print(f'\n===> To run: {picked}\n')
        if 'Quit' in picked:
            sys.exit(0)
        try:
            print('-- ALERT: DO NOT interrupt tasks or risk creating unfortunate issues\n')
            time.sleep(1.0)
            if dry_run:
                continue
            if 'root password' in picked:
                run_subcmd('set-password-root')
            elif 'user password' in picked:
                run_subcmd('set-password-user')
            elif 'Update Linux' in picked:
                run_subcmd('update-linux')
            elif 'Refresh Icons' in picked:
                run_subcmd('refresh-icons')
            elif 'Enable Flatpak' in picked:
                run_subcmd('enable-flatpak')
            elif 'Cleanup Flatpak' in picked:
                run_subcmd('cleanup-flatpak')
            elif 'Purge Flatpak' in picked:
                run_subcmd('purge-flatpak')
            elif 'Disable LibreOffice File Locking' in picked:
                run_subcmd('disable-libreoffice-file-locking')
            elif 'Stable' in picked:
                run_subcmd('set-debian-stable')
            elif 'Testing' in picked:
                run_subcmd('set-debian-testing')
            elif 'Unstable' in picked:
                run_subcmd('set-debian-unstable')
        except KeyboardInterrupt:
            pass

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("Shutdown requested, so exiting ...")
        sys.exit(15)

    except Exception as exc:
        if not isinstance(exc, BrokenPipeError):
            print("Caught exception running main(), so exiting ...")
            print(traceback.format_exc())
        sys.exit(15)

    sys.exit(0)
